### ISSUE TITLE
什么时候能开源呢？

### ISSUE THREAD

**Issue by poorfriend** [automan000/Camera-based-Person-ReID#1]
RT

**Comment by poorfriend** [comment]
我对你的文章很感兴趣， 你文章中只有PCB和BoT的加上你们方法的结果， 有比如MGN和ABD之类更强模型加上你们方法的结果吗？

**Comment by automan000** [comment]
感谢关注。Code已开源。我们目前没有测试过MGN和ABD等网络结构。
