### ISSUE TITLE
关于训练损失函数的设计

### ISSUE THREAD

**Issue by justopit** [automan000/Camera-based-Person-ReID#11]
这是一个非常棒的工作，通过对齐不同摄像机的统计量来获得巨大的性能提升。然而我注意到你的损失函数为CrossEntorpyLoss，并且你的Sampler为IdentitySampler，那么你为什么不加上Triplet Loss呢？加上Triplet Loss是会引起你模型性能的下降吗？我训练了fastreid的模型，并且在测试的时候使用了你的CBN，发现模型mAP直接到了个位数，无论是跨域还是supervised，这是否表明你的CBN依靠于一种固定的训练策略？

**Comment by automan000** [comment]
我觉得应该是您哪里搞错了。我们的论文里有与[Bag of Tricks](https://arxiv.org/abs/1903.07071)结合的实验结果，性能是提升的。BoT使用了Triplet Loss。

我们这个工作的本意是为了展示对齐Camera数据分布的重要性。为了控制变量，网络结构、目标函数、训练策略都尽可能地进行了简化，所以没有使用triplet loss。

此外，根据您的上一个问题，我觉得您可能没有注意到训练阶段的变化。训练阶段的采样策略也需要进行相应的修改。不能直接把我们的测试代码应用在别人已训练的模型上。

**Comment by justopit** [comment]
嗯嗯呢。谢谢您的回复。我还想再问一个问题。你在readme.md中有写到在test的时候会将所有的BN的momentum设置为None，然而我却没有在test_model.py中明显地看到这个设置。我只在build model时候，看到最后一层BN设置为None。

**Comment by automan000** [comment]
https://github.com/automan000/Camera-based-Person-ReID/blob/master/frameworks/models/backbone/resnet_backbone.py

**Comment by justopit** [comment]
> https://github.com/automan000/Camera-based-Person-ReID/blob/master/frameworks/models/backbone/resnet_backbone.py

Thank you very much. 那您在训练的时候，也是设置momentum为None？我在train_model.py那里没有明显看到设置为0.1

**Comment by automan000** [comment]
是的。

**Comment by justopit** [comment]
> 是的。

谢谢大佬的快速回复。

**Comment by automan000** [comment]
客气了
