### ISSUE TITLE
关于训练阶段使用CBN

### ISSUE THREAD

**Issue by xmy0916** [automan000/Camera-based-Person-ReID#13]
作者您好！看了您的论文，感觉这是一个很不错的工作，我看您消融实验部分table6有关于训练阶段使用CBN方法的效果，有点困惑，请问训练阶段怎么使用CBN呢？是在每个epoch前采样每个相机图像的均值和方差参数吗？

**Comment by automan000** [comment]
我们的核心观点是统计量的计算应该被限制在同一个相机内，而不是跨相机。在训练阶段，BN是从所有相机里随机采样，不满足我们的需求。对于CBN训练，只要保证每一个mini-batch里的图像，都来自同一个相机，就可以了。

**Comment by xmy0916** [comment]
@automan000 感谢您的回复，还有一个问题，请问测试的时候统计10次的目的是什么呢？测试不同的随机种子吗？

**Comment by automan000** [comment]
每个实验进行了10次重复实验，是为了尽可能消除随机种子的选取对实验结果的影响。测试的时候不是统计了10次，是随机选了10个mini-batch算统计量，详情见Table.7

**Comment by xmy0916** [comment]
明白啦～感谢，但是我觉得minibatch中如果图像都来自一个相机不会影响reid模型对跨相机图片同id识别的能力吗？

**Comment by automan000** [comment]
这个问题，我建议您再读一下我们的文章

**Comment by xmy0916** [comment]
好的～
