### ISSUE TITLE
About weakly-supervised learning and incremental learning.

### ISSUE THREAD

**Issue by Kingaslan** [automan000/Camera-based-Person-ReID#5]
Hi, I am appreciated for the work you have done. 
I am really interested in the weakly-supervised learning and incremental learning parts, which are not released. Will it be released in the future?

**Comment by automan000** [comment]
Hi, thanks for your attention. To help future researches, we keep this repo as simple as we can.
About the weakly-supervised and incremental learning parts, we have no plan to release the code, at least in this repo.
I think you can implement these parts based on this repo. It is quite simple (but will make this repo ugly) and I am sure that you can achieve our reported results if you follow the instructions in our supplementary materials.
