### ISSUE TITLE
关于CamDataParallel

### ISSUE THREAD

**Issue by datuizhuang** [automan000/Camera-based-Person-ReID#7]
代码中的重点应该是CamDataParallel对吧？请问如果要用distributedDataParallel，我应该怎么修改呢？

**Comment by automan000** [comment]
目前的做法是为了适应ReID的Data Sampler需要保证每个人4张图像而设计的。

如果不需要这个约束，你可以直接使用distributedDataParallel，然后让每一个mini-batch中的Camera数量恰好等于GPU数量，并且保证每一个Camera对应的图像分发到相同的GPU上。这样可以天然地利用“PyTorch BN的统计量在GPU之间不共享”的“特性”达到分别统计Camera统计量的目的。测试阶段则可以直接使用我们的代码在一个GPU上进行。

**Comment by datuizhuang** [comment]
好的谢谢，在我自己的当前采样器的基础上大致改了一下，有时间跑一跑。
测试的时候一个GPU么？ 那测试代码里的Dataparallel有什么用么？
我在DataParallel下用多个GPU效果一样的吧？

**Comment by automan000** [comment]
测试阶段用Data Parrallel包裹一下是为了方便加载训练好的模型。

多GPU测试的情况详见https://github.com/automan000/Camera-based-Person-ReID/issues/4 。

如果你是在用ReID公共数据集的话，仅仅按照Camera ID构造mini-batch可能会出现较为明显的性能衰减。相关采样策略需要仔细设计。现在的CamDataParallel就是权衡ID Sampler和Cam Sampler之后的产物。总之，采样问题还有很多坑要填。

**Comment by datuizhuang** [comment]
数据集有公共的，也有自己的。
为了按照cam id采样，改完之后比我之前的确实随意了不少哈哈，有时间先试试着。
