### ISSUE TITLE
A larger model will cause loss to converge hard?

### ISSUE THREAD

**Issue by HollrayChan** [automan000/Camera-based-Person-ReID#9]
Hello, I reproduced the results of the paper on the two data sets of market and duke. I tried to use this method in my own larger network, but xent became difficult to converge. Have you tried other Is the baseline, for example strongbaseline, a larger model will make it difficult for loss to converge?

**Comment by automan000** [comment]
We have tested strongbaseline (BoT). Please see our paper for more details. 
Our experiments show that all ResNet variants, such as ResNet-18, 34, 50, 101, can benefit from our work.
However, we haven't tested recent sophisticated ReID networks. 
They may require much more delicate optimizing strategies, which can be very different from the configurations in their original works.

**Comment by HollrayChan** [comment]
Thx a lot！I'll try to test in other types of networks.
